### ISSUE TITLE
Should zip data be kept inside the package ? 

### ISSUE THREAD

**Issue by raphaeleadjerad** [InseeFrLab/pynsee#10]
Some files are zipped into the package, should they be left as such ? Or requested from given links using appropriate functions ?  

**Cons**
- heavy package
- possibility that the underlying files, hence data, may change
- ownership problem (gregoiredavid geojson for instance)

**Pros**
- backup if underlying file disappears from source or is changed from place

**Comment by hadrilec** [comment]
The new module geodata adbedf50d2f4e2689fa9a42e2a99654cadee99db, allows users to download geographical data from IGN's API, package's internal data has been reduced significantly. Only the minimal data is now kept inside the package. I consider this issue as closed.
