### ISSUE TITLE
How to find latest local data?

### ISSUE THREAD

**Issue by tfardet** [InseeFrLab/pynsee#115]
Maybe I don't understand exactly how ``pynsee`` works but there does not seem to be a way to update the information about local metadata (i.e. about https://api.insee.fr/donnees-locales/).

When I call ``get_local_metadata`` I get the 

```
!!! This function renders only package's internal data,
it might not be the most up-to-date
Have a look at api.insee.fr !!!
```
message and old metadata (e.g. "GEO2020RP2017" while the most recent seems to be "GEO2022RP2019").

Is there a way to get a ``get_local_metadata`` equivalent that fetches the latest data from the INSEE API?

On a somewhat similar note, is there a way to know automatically what the latest version of a dataset is?
For instance, if I want to work with the most recent data from FLORES and the RP, how can I call ``get_local_data`` on the most recent dataset? Is there something like ``GEOlatestRPlatest``?

I could just try all dates and ignore calls that return empty dataframes but that is quite cumbersome.

**Comment by hadrilec** [comment]
Hello,

`get_local_metadata` provides metadata coming from internal package data. Consequently, when there is an update of the metadata on api.insee.fr,  `pynsee` should also be update but it cannot occur straight after the metadata publication as this package maintained on a best effort basis.
Please note that the following functions : `get_nivgeo_list`, `get_geo_list`, `get_area_list`, might help you to find what are the values needed to use `get_local_data`.

`get_local_data` returns data according to the argument the user provides. If the values are the last ones according to the metadata available on api.insee.fr, the function should be able to return the latest data available.

The following examples are working for me, so it should be the case for you as well:

`from pynsee.localdata import get_local_data`

`dataFrance = get_local_data(dataset_version='GEO2022FLORES2019',                           
                           variables =  'NA5-EFFECSAL5T_0_50P')`

`dataParis = get_local_data(dataset_version='GEO2022FLORES2019',                           
                           variables =  'NA17',
                           nivgeo='COM',
                           geocodes = ['75056'])`

`dataFrance = get_local_data(dataset_version='GEO2022RP2019',                           
                           variables =  'TF4')`

`dataParis = get_local_data(dataset_version='GEO2022RP2019',                           
                           variables =  'TYPMR',
                           nivgeo='COM',
                           geocodes = ['75056'])`

Should you need any further explanation let me know.

**Comment by hadrilec** [comment]
Local Data API is overall not easy to use, `pynsee.localdata` depends on it.
If you still have difficulties using it, you may try to use `pynsee.download`, see the following examples:

- [marie as first name over time](https://pynsee.readthedocs.io/en/latest/examples/example_marie_firstname.html)

- [housing construction period](https://pynsee.readthedocs.io/en/latest/examples/example_rp_logement_2017.html)

- [upper and middle class workers in IDF](https://pynsee.readthedocs.io/en/latest/examples/example_cadre_iris_idf.html)

**Comment by tfardet** [comment]
Sorry, my question was probably poorly formulated.
I can use ``get_local_data`` just fine, I'm trying to understand how I can know what the latest datasets are and how to get them.
Because I cannot do this with ``get_local_metadata``, I basically have to try random years until I get something that works so I was wondering whether there would be a way to do that automatically such that a given code would always give results using the latest data.

**Comment by hadrilec** [comment]
Hi @tfardet,

I have just pushed a new version of `get_local_data` implementing the solution you hinted at.

Whenever `GEOlatestRPlatest` (RP is used as an example) will be used, the function will trigger a loop to find the latest combination of geographic and quantitative data dates available. This new feature is already available on the master branch, and will be available on Pypi in a future release.

Thanks for this idea.

**Comment by tfardet** [comment]
Amazing, will check it out, thanks!

**Comment by tfardet** [comment]
OK, the API is working again for me so I was finally able to test the code.
It seems to work for my codes, though the specific  example you provided does not:

```python
 df = get_local_data(dataset_version='GEOlatestRPlatest', variables = 'CS1_6')
```

Only prints

```
Finding Latest Dataset Version:  36%|███████████████████████████████████████████████████▊                                                                                            | 9/25 [00:02<00:04,  4.00it/s]
```

and leads to df containing 
```
  CODEGEO  OBS_VALUE
 0       1        NaN
```

while the normal message for working code is

```
Finding Latest Dataset Version:  36%|███████████████████████████████████████████████████▊                                                                                            | 9/25 [00:02<00:03,  4.12it/s]
Getting data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 6932.73it/s]
```

**Comment by tfardet** [comment]
Also, while this works well for single calls, it becomes very slow for repeated calls since the loop is performed on each call.
Maybe caching the last loop date for each dataset and only performing the loop once a day (week/month?) would be a plus.

**Comment by tfardet** [comment]
Also, in ipython and jupyter, I sometime get "frozen results" where the line/cell seemingly executes but the code does not exit properly from the "latest" loop.

This is most visible in ipython, where subsequent lines do not execute (you can hit "enter" and you get a new line, but no ``Out`` and no execution or error is raised... I can type

```python
In [1]: 2.12*"abc"  # and this will just give me
In [2]:             # after I press "enter" instead of insulting me with a TypeError
```

**Comment by hadrilec** [comment]
I close this issue, as I think it is now fine.
@tfardet feel free to reopen one if any new feature is needed
