### ISSUE TITLE
Use logging instead of print

### ISSUE THREAD

**Issue by tfardet** [InseeFrLab/pynsee#117]
It would be nice to have the ability to hide messages from pynsee.
This would be possible if  logging was used rather than calls to print (e.g. for [cached data](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/utils/_warning_cached_data.py#L6) or during [requests](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/utils/_request_insee.py#L13).

With a logger, the importance of each log could be set independently (e.g. messages about the use of cached data could be INFO while some issues with requests would be WARNING, ERROR, or CRITICAL) which would let people filter the levels they don't care about.

If necessary, the default visibility can be set to INFO so that all messages are still printed when nothing is changed.

Cf. https://docs.python.org/3/howto/logging.html for examples.

**Comment by lgeo3** [comment]
I'll be happy to work on this one, it seems to be a good issue for a first contribution if you agree ?

**Comment by tfardet** [comment]
Ah yes, that would be great, I thought I'd have time to work on pynsee for a bit but that did not happen, unfortunately... will be happy to review a PR, though :)
