### ISSUE TITLE
Install from git using poetry

### ISSUE THREAD

**Issue by tgrandje** [InseeFrLab/pynsee#128]
I'm having trouble installing the package from git using poetry.

I get the following traceback :
```
Because pynsee (0.1.2) @ git+https://github.com/InseeFrLab/pynsee@master depends on pathlib (*) which doesn't match any versions, pynsee is forbidden.
So, because ssp-scraping depends on pynsee (0.1.2) @ git+https://github.com/InseeFrLab/pynsee@master, version solving failed.
```

This seems to be related to the "requirements.txt" specifying built-in packages (pathlib and urllib3).

As I usually rely on poetry to build packages, I'm not 100% sure : is this syntax standard practice? (I've seen some posts here and there about this being bad practice, but those where mostly pieces of opinion, not reputable sources).

(I'm ok with doing the PR if confirmed, just not wanting to break anything...)

**Comment by tgrandje** [comment]
Btw, to proceed to install with poetry :

A workaround could be to install with pip *through poetry* as explained in the readme. Note that you can't cd to the directory without breaking the reference to poetry's toml.
```
git clone https://github.com/InseeFrLab/pynsee.git
poetry run pip install .[full]
```
(I haven't been able to proceed with a one-shot in the `poetry run pip install pynsee[full] git+install https://...` way)

**Comment by hadrilec** [comment]
I removed pathlib from requirements.txt and setup.py.
Could you please check again whether it is working or not?

**Comment by tgrandje** [comment]
Works like a charm, thank you 👍
