### ISSUE TITLE
pynsee.localdata.get_geo_list doesn't keep "CHEFLIEU" columns if geo is not "region"

### ISSUE THREAD

**Issue by tgrandje** [InseeFrLab/pynsee#136]
Hello Hadrien
I see that get_geo_list returns a dataframe with "CHEFLIEU" as a column, but that is not the case if you ask for (say) a departement.
I've tracked it down to [line 172](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/localdata/get_geo_list.py#L172) and that seems intentional.
Do you have objections to me setting a PR regarding that behaviour ?
Thanks

**Comment by hadrilec** [comment]
@tgrandje ok fine, yes please make a PR I will review it whenever I have a bit of time, thanks a lot

**Comment by tgrandje** [comment]
https://github.com/InseeFrLab/pynsee/pull/137

**Comment by tgrandje** [comment]
Just done my PR (which will also includes the PR about the logger, sorry about that...).

**Comment by hadrilec** [comment]
solved by #142
