### ISSUE TITLE
Can't init connection anymore?

### ISSUE THREAD

**Issue by maggiemhanna** [InseeFrLab/pynsee#149]
When I try to establish a connection with API using

from pynsee.utils.init_conn import init_conn
init_conn(insee_key="insee_key", insee_secret="insee_secret", http_proxy="", https_proxy="")

ValueError: !!! Token is missing, please check insee_key and insee_secret are correct !!!

Everything was working fine a couple of days ago. Not anymore.

I tried refreshing tokens, and clearing cache using:
from pynsee.utils import clear_all_cache; clear_all_cache()

Nothing is working.

**Comment by tgrandje** [comment]
Are you working behind a corporate proxy ? Did you update pynsee recently and/or what version are you using ?

**Comment by hadrilec** [comment]
hi @maggiemhanna,
I confirm that there is an issue, but it is related the insee's API itself.
On insee.api.fr I created a new app and I could not generate new credentials for this app.
I will raise a ticket through the contact form, I would encourage users to do the same.

**Comment by hadrilec** [comment]
Nevertheless, pynsee.geodata and pynsee.download modules should still be usable as they dont require prior authentication

**Comment by maggiemhanna** [comment]
Hello, 
I'm not using any proxy.
I will raise a ticket through the contact form. 
Thanks a lot.

**Comment by hadrilec** [comment]
INSEE API is back on track since this morning
