### ISSUE TITLE
sirene module should be tested with the new api release v3.11

### ISSUE THREAD

**Issue by hadrilec** [InseeFrLab/pynsee#158]
https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=Sirene3&version=V3.11&provider=insee

**Comment by hadrilec** [comment]
more info here:
https://www.insee.fr/fr/information/6525081

**Comment by hadrilec** [comment]
according to INSEE's calendar, API switch to version 3.11 will occur end of March 2014
https://www.sirene.fr/sirene/public/static/sirene4

**Comment by tfardet** [comment]
is this fixed by 0865c13814ba92f6916e0743e585f930bbe87cab ?

**Comment by hadrilec** [comment]
not yet, changes were made in branch sirene-v4 f99ffad
