### ISSUE TITLE
geodata returns exception traceback as dataframe (missing rights)

### ISSUE THREAD

**Issue by tgrandje** [InseeFrLab/pynsee#161]
```
from pynsee.geodata import get_geodata
com = get_geodata("ADMINEXPRESS-COG-CARTO:commune")
print(com.to_json())
>>>    {"status":{"0":403},"comment":{"0":"<ExceptionReport><Exception exceptionCode=\"MissingRights\">No rights for this ressource or ressource does not exist<\/Exception><\/ExceptionReport>"}}
```

The link prepared by geodata/_get_geodata.py is :
'https://wxs.ign.fr/administratif/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAME=ADMINEXPRESS-COG-CARTO:commune&srsName=EPSG:3857&OUTPUTFORMAT=application/json&COUNT=1000'

**Comment by hadrilec** [comment]
Hi,

I have noticed some weird output from this data identifier. 
I would suggest to use the following code:

```
from pynsee import *
com = get_geodata('ADMINEXPRESS-COG-CARTO.LATEST:commune')
```
