### ISSUE TITLE
Add an `exact_location` field for SIRENE DataFrames with `get_location`

### ISSUE THREAD

**Issue by tfardet** [InseeFrLab/pynsee#168]
Right now, there is no obvious way to check whether the location returned by [``get_location``](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/sirene/get_location.py#L40) is exact or not.

I'd propose to add a column with a title like "exact_location" that would be a boolean with ``True`` if the [first call to `get_location_openstreetmap`](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/sirene/get_location.py#L140) succeeds and ``False`` otherwise.

**Comment by hadrilec** [comment]
#170 has been merged, the issue should be fixed

**Comment by tfardet** [comment]
I was looking at it, so will propose an additional PR to add some documentation and caching.
Is there a reason why the function is declared in a separate file and not directly as a ``SireneDataFrame`` method? Should I move it there?

**Comment by hadrilec** [comment]
indeed, I forgot to improve the related doc, thanks
as far as I understand, the `get_location` function is imported inside the class, and hence becomes a method of the class, isn't it?

**Comment by tfardet** [comment]
@hadrilec sure, but why make an extra file instead of having it directly in [``SireneDataFrame``](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/sirene/SireneDataFrame.py)?
Also it is a bit strange to have a lonely method with a ``self`` argument.
It's not technically a problem, just feels a little weird so I would propose to move it into the same file unless there is a good reason not to do so...
