### ISSUE TITLE
url used to download the list of macroeconomic series has changed

### ISSUE THREAD

**Issue by hadrilec** [InseeFrLab/pynsee#176]
Once I am back from holidays, I will make a permanent fix by end of November.

**Comment by hadrilec** [comment]
the issue should be solved as insee switched back to the previous naming convention

**Comment by tfardet** [comment]
Do you know whether other changes have occurred?
Looking at the failing builds, there seem to be a few issues with `metadonnees`-related URLs

See :

- https://github.com/InseeFrLab/pynsee/actions/runs/6517461855/job/17771520089#step:7:461
- https://github.com/InseeFrLab/pynsee/actions/runs/6888365365/job/18737215711?pr=162#step:7:245

**Comment by hadrilec** [comment]
the following commit solved the problem you raised which is more related to the PR #162 than this issue: 0afbd0f3c406563f30cad14b9de5bf7599209dbe
in any case, insee corrected the error, so all fine
