### ISSUE TITLE
macrodata series list: some series dont exist after INSEE's unexpected update

### ISSUE THREAD

**Issue by hadrilec** [InseeFrLab/pynsee#197]
Insee changes macrodata time series identifiers and sometimes forget to change the identifiers in the official list which leads to bugs. One possible solution would be to try automatically to add a dot at the end of the series identifier in case the first try fails.

**Comment by tfardet** [comment]
> One possible solution would be to try automatically to add a dot at the end of the series identifier in case the first try fails.

I did not get that, could you explain why the dot would help? Is there a pattern to the changes made by the INSEE?

**Comment by hadrilec** [comment]
yes indeed, they decided to add a dimension to the time series at the end of the identifier. So two series might exist like myid.TRUE and myid.FALSE, adding a dot would mean that you want to retrieve the data on the two series.

**Comment by tfardet** [comment]
OK, thanks!
If this is documented somewhere, it would also be good to add a link to it so the rationale doesn't get lost.

**Comment by hadrilec** [comment]
this PR #199 should fix the issue
