### ISSUE TITLE
not updated data ?

### ISSUE THREAD

**Issue by fbmfbm** [InseeFrLab/pynsee#198]
Hi,
Great work but what about updated data ? 
If i try "get_files_list" function and filter on FILOSOFI data, only 2017 files are returned. 
2017 to 2020 data ore on the INSEE site.

Any help about this ?

Thank's

**Comment by hadrilec** [comment]
Hi,
the list is from the repo [Doremifasol](https://github.com/InseeFrLab/DoReMIFaSol).
It is updated by kind benevolent contributors, as Insee does not provide this list.
Consequently, I would kindly suggest you to find the links on insee.fr, and then you could raise an issue on Doremifasol repo asking for the links you might find to me added to the list.

Best

**Comment by fbmfbm** [comment]
Than'ks,
i'll try to submit update on Doremifasol repo

Bye
