### ISSUE TITLE
Bug installation from github using  sspcloud

### ISSUE THREAD

**Issue by raphaeleadjerad** [InseeFrLab/pynsee#23]
Cannot install from github directly using sspcloud, probleme installing pyYAML : 
"ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

**Comment by hadrilec** [comment]
Using the following command : pip install git+https://github.com/InseeFrLab/Py-Insee-Data.git#egg=pynsee
I was not able to reproduce the error.
Do you still have the error when you try to install the package?

**Comment by hadrilec** [comment]
No longer an issue. I close.
