### ISSUE TITLE
fix tests for better ci (quality)

### ISSUE THREAD

**Issue by cthiounn** [InseeFrLab/pynsee#38]
pynsee's pipeline are in errors since august. Best practices advise to keep it working in order to detect bugs and regressing code. 

It seems there are two errors, one minor and one bigger : 

minor : a small typo indentation in test_pynsee_sirene.py
complex : the test of the download of the census data is not working, because pandas in the github runner cannot achieve to load the 4gb CSV file

**Comment by linogaliana** [comment]
- Thanks for digging into our CI problems. Yes you are right with the RP problem. Given the current implementation of `telechargerDonnees` (name will be changed, see #37) it is not trivial. A workaround could be to add a `nrow` argument to the function that would be passed to `pandas` to avoid trying read the entire file

**Comment by linogaliana** [comment]
However, maybe that would make more sense not to test `telechargerDonnees` with RP. We could just check the `requests` 200 code to be sure we could find the dataframe if needed
