### ISSUE TITLE
Proxy server - make sure the package is working inside insee's premises ie behind proxy server

### ISSUE THREAD

**Issue by hadrilec** [InseeFrLab/pynsee#81]

**Comment by hadrilec** [comment]
@tgrandje do you work behind a proxy server? 
if yes, could you please try to test that pynsee is usable behind this proxy server?
Thanks,

**Comment by tgrandje** [comment]
@hadrilec I do and it works (proxy configuration was the main reason I asked you about the future release's date). I'll check it tomorrow again (with poetry and the current master version) just to be sure.
@linogaliana do you still have troubles running pynsee ?

**Comment by tgrandje** [comment]
@hadrilec I confirm this is working behind my corporate proxy.

**Comment by hadrilec** [comment]
@tgrandje thanks a lot
