### ISSUE TITLE
Problem with RP_LOGEMENT year 2017

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/pynsee#90]
Problem encountered when using 

```python
dataframe_pynsee=load_data("RP_LOGEMENT", date = "2017")
```

**Comment by hadrilec** [comment]
#91 should correct this problem

**Comment by hadrilec** [comment]
Solved, example Construction Period shows it is fine cc8e87b704ef9c97db24e446d98fe4c51c71d891
